#!/bin/sh

if [ -z "$1" ]; then
	echo "usage: $(basename $0) <data dir>" >&2
	exit 1
fi

data_dir="$1"
if [ ! -d "$data_dir" ]; then
	echo "error: $data_dir does not exist" >&2
	exit 1
fi

find "$data_dir" -name "*.mp4" -mtime +4 -printf '%P\n' | while read filename; do
	if [ -f "$data_dir/$filename" ]; then
		rm -f "$data_dir/$filename"
	fi
done
