#!/bin/sh

if [ -z "$1" ]; then
	echo "usage: $(basename $0) <data dir>" >&2
	exit 1
fi

if [ -z "$GORL_ADDRESS" ]; then
	echo "error: GORL_ADDRESS is missing in environment" >&2
	exit 1
fi
if [ -z "$GORL_USERNAME" ]; then
	echo "error: GORL_USERNAME is missing in environment" >&2
	exit 1
fi
if [ -z "$GORL_PASSWORD" ]; then
	echo "error: GORL_PASSWORD is missing in environment" >&2
	exit 1
fi

data_dir="$1"
if [ ! -d "$data_dir" ]; then
	echo "error: $data_dir does not exist" >&2
	exit 1
fi

lock_file="/tmp/gorl.lock"
if [ -f "$lock_file" ]; then
	echo "error: $(basename $0) is already running" >&2
	exit 1
fi
touch $lock_file

tmp_file="$(mktemp)"
gorl ls | tail -n+2 >"$tmp_file"

db_file="$data_dir/.db.txt"
if [ ! -f "$db_file" ]; then
	touch "$db_file"
fi

cat $tmp_file | while read d t duration filename; do
	key="$filename|$duration"

	# Skip to the next entry if the key already exists in the db
	if grep -q "$key" "$db_file"; then
		continue
	fi

	# The filename has been downloaded before, but the duration has
	# changed. Remove the line from the db and download the file again
	if grep -q "$filename" "$db_file"; then
		tmp_db_file=$(mktemp)
		grep -v "$filename" "$db_file" >"$tmp_db_file"
		mv "$tmp_db_file" "$db_file"
	fi

	gorl dl -f "$filename" >"$data_dir/$filename"
	echo "$filename|$duration" >>"$db_file"
done

rm -f "$lock_file" "$tmp_file"
