#!/bin/sh

if [ -z "$1" ]; then
	echo "usage: $(basename $0) <data dir>" >&2
	exit 1
fi

if [ -z "$GORL_ADDRESS" ]; then
	echo "error: GORL_ADDRESS is missing in environment" >&2
	exit 1
fi
if [ -z "$GORL_USERNAME" ]; then
	echo "error: GORL_USERNAME is missing in environment" >&2
	exit 1
fi
if [ -z "$GORL_PASSWORD" ]; then
	echo "error: GORL_PASSWORD is missing in environment" >&2
	exit 1
fi

data_dir="$1"
if [ ! -d "$data_dir" ]; then
	echo "error: $data_dir does not exist" >&2
	exit 1
fi

lock_file="/tmp/gorl.lock"
if [ -f "$lock_file" ]; then
	echo "error: $(basename $0) is already running" >&2
	exit 1
fi
touch $lock_file

tmp_file="$(mktemp)"
gorl ls | tail -n+2 >"$tmp_file"

cat $tmp_file | while read d t duration filename; do
	fn=$(echo $filename | cut -d. -f1)
	end=$(echo $filename | cut -d. -f2)
	key="$fn"_"$duration"."$end"

	# Skip the file if it already exist
	if ls "$data_dir" | grep -q "$key"; then
		continue
	fi

	# The filename has been downloaded before, but the duration has
	# changed. Remove the line from the db and download the file again
	if ls "$data_dir" | grep -q "$fn"; then
		rm -f "$data_dir/$fn"*
	fi

	gorl dl -f "$filename" >"$data_dir/$key"
done

rm -f "$lock_file" "$tmp_file"
